### ISSUE TITLE
ERROR: add-banner --template banner.tmpl dist/*.*s Windows 10

### ISSUE THREAD

**Issue by dreitzner** [ain/smartbanner.js#142]
__Steps to reproduce__:

1. run build on master branch on windows 10 with node 8.15 & 8.17

__What happens__:

```
> add-banner --template banner.tmpl dist/*.*s

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\projects\smartbanner.js\dist\*.*s'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read (D:\projects\smartbanner.js\node_modules\add-banner\index.js:17:29)
    at module.exports (D:\projects\smartbanner.js\node_modules\add-banner\index.js:61:23)
    at bannerise (D:\projects\smartbanner.js\node_modules\add-banner\bin\add-banner.js:23:22)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\projects\smartbanner.js\node_modules\add-banner\bin\add-banner.js:32:14)
    at Module._compile (module.js:653:30)
    at Module.load (module.js:566:32)
```

__What should happen__:
build should pass

@ain do I need a different node version?
I would love to add a feature. BTW, I am pretty new to open source (not programming), how do I go about adding a pull request when everything passes? I can't seem to push my branch.

**Comment by ain** [comment]
Thanks for the report @dreitzner.

This is the unfortunate problem that has been highlighted before and relates to an external `add-banner` module, a fork of which needs a fix. There're jonschlinkert/add-banner#10, jonschlinkert/add-banner#12 and jonschlinkert/add-banner#13 open on related topics.

**Comment by ain** [comment]
Reproduced on CI in https://github.com/ain/smartbanner.js/runs/1387911367
