### ISSUE TITLE
3 Tests failing

### ISSUE THREAD

**Issue by fkoester** [ain/smartbanner.js#22]
I just noticed that 3 unit tests are failing on my system. Did not yet investigate it further. Is it a known problem?

```bash
$ npm run test       

> smartbanner.js@1.2.0 test /home/fabian/workspace/machtfit/smartbanner.js
> node_modules/mocha/bin/mocha --compilers js:babel-core/register test/spec/*.js



  Bakery
    bake
      ✓ expected to set cookie
    baked
      ✓ expected to return true if cookie is set
      ✓ expected to return false if cookie is not set
    unbake
      ✓ expected to remove cookie

  Detector
    platform
      when on iPhone
        ✓ expected to return ios
      when on iPad
        ✓ expected to return ios
      when on iPod
        ✓ expected to return ios
      when on Android
        ✓ expected to return android
    jQueryMobilePage
      without jQuery Mobile
        ✓ expected to return false
      with jQuery Mobile
        1) expected to return true
    marginedElement
      without jQuery Mobile
        ✓ expected to return html element as first item of array
      with jQuery Mobile
        2) expected to return ui-page element as first item of array

  OptionParser
    parse
      with smartbanner meta tags
        ✓ expected to parse title
        ✓ expected to parse author
        ✓ expected to parse price
        ✓ expected to parse iOS price suffix
        ✓ expected to parse Android price suffix
        ✓ expected to parse button label
        ✓ expected to parse iOS icon
        ✓ expected to parse Android icon
        ✓ expected to parse iOS button URL
        ✓ expected to parse Android button URL
        ✓ expected to parse enabledPlatforms option
      without smartbanner meta tags
        ✓ expected to return empty object
      without any meta tags
        ✓ expected to return empty object

  SmartBanner
    publish
      without options
        ✓ expected to throw error
      with options
        when on iPhone
          ✓ expected to add iOS template to body
          ✓ expected to store original top margin
        when on iPad
          ✓ expected to add iOS template to body
        when on iPod
          ✓ expected to add iOS template to body
        when on Android
          ✓ expected to add Android template to body
        when on desktop
          ✓ expected to not add anything to body
      when has been closed within current session
        ✓ expected to not to add to body
      when has been closed, but is reopened in new session
        ✓ expected to add to body
      when enabled-platform set to android, but opened on iOS
        ✓ expected to not add anything to body
      when enabled-platform set to ios, but opened on Android
        ✓ expected to not add anything to body
    template
      when on iPhone
        ✓ expected to work against iOS platform
        ✓ expected to have iOS price suffix
        ✓ expected to return iOS template
        ✓ expected to have iOS icon
        ✓ expected to have iOS button URL
      when on iPad
        ✓ expected to work against iOS platform
        ✓ expected to have iOS price suffix
        ✓ expected to return iOS template
        ✓ expected to have iOS icon
        ✓ expected to have iOS button URL
      when on iPod
        ✓ expected to work against iOS platform
        ✓ expected to have iOS price suffix
        ✓ expected to return iOS template
        ✓ expected to have iOS icon
        ✓ expected to have iOS button URL
      when on Android
        ✓ expected to work against Android platform
        ✓ expected to have Android price suffix
        ✓ expected to return Android template
        ✓ expected to have Android icon
        ✓ expected to have Android button URL
    exit
      without jQuery Mobile
        ✓ expected to set cookie
        ✓ expected to remove component markup
        ✓ expected to restore HTML margin
      with jQuery Mobile
        3) expected to restore top distance
    height
      ✓ expected to match component offset height


  58 passing (415ms)
  3 failing

  1) Detector jQueryMobilePage with jQuery Mobile expected to return true:
     AssertionError: expected false to be true
      at Context.<anonymous> (test/spec/detector_spec.js:111:9)

  2) Detector marginedElement with jQuery Mobile expected to return ui-page element as first item of array:

      AssertionError: expected { Object () } to deeply equal { Object () }
      + expected - actual

      
      at Context.<anonymous> (test/spec/detector_spec.js:148:49)

  3) SmartBanner exit with jQuery Mobile expected to restore top distance:

      AssertionError: expected 12 to deeply equal NaN
      + expected - actual

      -12
      +NaN
      
      at Context.<anonymous> (test/spec/smartbanner_spec.js:496:24)




npm ERR! Linux 4.8.12-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! smartbanner.js@1.2.0 test: `node_modules/mocha/bin/mocha --compilers js:babel-core/register test/spec/*.js`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.2.0 test script 'node_modules/mocha/bin/mocha --compilers js:babel-core/register test/spec/*.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/mocha/bin/mocha --compilers js:babel-core/register test/spec/*.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smartbanner.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fabian/workspace/machtfit/smartbanner.js/npm-debug.log
```

**Comment by fkoester** [comment]
Using commit `a31b4b449601f816ca09768224053ba450251e43` on branch `master`

**Comment by ain** [comment]
Thanks for reporting.

I've just ran on `6.2.0` and `6.9.0` and all 61 are passing. Could you try to reset your `node_modules` and retry?

**Comment by fkoester** [comment]
Still failing with `$ rm -rf node_modules && npm install && npm run test`

**Comment by fkoester** [comment]
I will debug it.

**Comment by fkoester** [comment]
My fault, I forgot to run `bower install`, so there was no jquery present.

I added a PR which adds some hints about this to the `README` and also a npm run script for easily running both, `npm install` and `bower install`:

https://github.com/ain/smartbanner.js/pull/24

**Comment by ain** [comment]
Excellent, thanks for the heads up!
