### ISSUE TITLE
Angular 2+ compatibility

### ISSUE THREAD

**Issue by KyleVassella** [ain/smartbanner.js#512]
How can we call smartbanner.publish() from an Angular component rather than a <script> tag in index.html? Is this library compatible with Angular projects?

__Steps to reproduce__:

1. Follow the setup instructions in an Angular 2+ project (including the scripts in angular.json file)
2. Run your default Jasmine/Karma unit tests (in many CICD processes, these are required to pass in order for your project to build)
3. Unit tests fail, one at a time, with the error message **Error: No options detected. Please consult documentation.** If the failing test is commented out, the next test will fail with the same error message.

__What happens__:
Unit tests fail with the following error message: **Error: No options detected. Please consult documentation**.

**Full error message/stack trace:**
_Error: No options detected. Please consult documentation.
    at SmartBanner.publish (http://localhost:9876/_karma_webpack_/webpack:/node_modules/smartbanner.js/dist/smartbanner.min.js:5:12695)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/smartbanner.js/dist/smartbanner.min.js:5:4326
    at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:406:1)
    at Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:178:1)
    at ZoneTask.invokeTask [as invoke] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:487:1)
    at invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:1600:1)
    at globalZoneAwareCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:1626:1)_
    
__What should happen__:
Unit tests should pass so that CICD builds can successfully complete.

**Comment by ain** [comment]
There's no need to run the `smartbanner.js` tests as part of your CI/CD pipeline since the tests are there in this project for the module itself.

It's the best practice not run the tests of all dependencies in your project since you may hit hundreds of different dependencies as the project grows. That will become time-consuming and/or expensive to do so at very little gain.

Ideally you'd only need to use the distribution files in `dist/` to implement `smartbanner.js` on your solutions.

For the above given reasons, closing the issue.
