### ISSUE TITLE
'npm run bannerise' issue on Windows 10

### ISSUE THREAD

**Issue by Ricco1** [ain/smartbanner.js#56]
Hi @ain,

'npm run bannerise' on Windows 10 (and might be others as well) is giving 'Error: ENOENT: no such file or directory, open `C:\Users\rihards.neimanis\Projects\smartbanner.js\dist\*.*s`'. My assumption is that windows just does not understand the regex \*.*s

**The full error description**:

Error: ENOENT: no such file or directory, open 'C:\Users\rihards.neimanis\Projects\smartbanner.js\dist\*.*s'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at read (C:\Users\rihards.neimanis\Projects\smartbanner.js\node_modules\add-banner\index.js:17:13)
    at module.exports (C:\Users\rihards.neimanis\Projects\smartbanner.js\node_modules\add-banner\index.js:70:25)
    at bannerise (C:\Users\rihards.neimanis\Projects\smartbanner.js\node_modules\add-banner\bin\add-banner:22:26)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\rihards.neimanis\Projects\smartbanner.js\node_modules\add-banner\bin\add-banner:28:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smartbanner.js@1.5.2 bannerise: `add-banner --template=banner.tmpl dist/*.*s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smartbanner.js@1.5.2 bannerise script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rihards.neimanis\AppData\Roaming\npm-cache\_logs\2017-07-15T16_28_06_525Z-debug.log

KR,

Ricco

**Comment by ain** [comment]
@Ricco1 what was Node.js version that you've used? Have you tried on `v7.10.0` or greater?

**Comment by Ricco1** [comment]
@ain now I am on `v4.7.2` and can't go up higher as I am tied up to some projects, which on later versions will not work.

**Comment by ain** [comment]
I see. The minimum requirement that we're currently supporting is [v6.2.0](https://github.com/ain/smartbanner.js/blob/master/package.json#L29) with a plan to add support for v8, see #57. 

I'm not sure if this is the reason here, but I'd be grateful for the feedback. It can easily be. If you're using NVM, it should be relatively easy to test.

**Comment by ain** [comment]
Since backwards compatibilty for `v4.7.2` is not planned and support for `v8` was just launched, I'm closing the topic.
